from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
import os
import json
from pydantic import BaseModel
from typing import List, Dict, Any
from langchain_core.messages import HumanMessage

from agent.graph import create_agent_graph, get_llm
from agent.state import AgentState
from langgraph.checkpoint.memory import MemorySaver

# The global in-memory checkpoint for chat persistence
memory_saver = MemorySaver()

app = FastAPI(title="AgentStack Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, WebSocket] = {}

    async def connect(self, websocket: WebSocket, user_id: str):
        await websocket.accept()
        self.active_connections[user_id] = websocket

    def disconnect(self, user_id: str):
        if user_id in self.active_connections:
            del self.active_connections[user_id]

    async def send_message(self, message: str, user_id: str):
        if user_id in self.active_connections:
            await self.active_connections[user_id].send_text(message)

manager = ConnectionManager()

# Basic Health Check
@app.get("/health")
def health_check():
    return {"status": "ok"}

# Mock function for position retrieval
def mock_get_positions(address: str):
    return {
        "_health_factor": 2.0,
        "_utilisation_rate": 50.0,
        "Aave": {"supplied": 1000}
    }

@app.websocket("/ws/chat/{user_address}")
async def websocket_endpoint(websocket: WebSocket, user_address: str):
    await manager.connect(websocket, user_address)
    
    # Initialize the LangGraph agent for this session
    llm = get_llm()
    # In a real app, tools would be loaded via the registry
    tools = [] 
    workflow = create_agent_graph(llm, tools, mock_get_positions)
    agent_app = workflow.compile(checkpointer=memory_saver)
    
    config = {"configurable": {"thread_id": user_address}}
    
    try:
        while True:
            data = await websocket.receive_text()
            
            # The initial state payload
            state = {
                "user_address": user_address, 
                "positions": {}, 
                "pending_actions": [], 
                "health_factor": 0.0, 
                "utilisation_rate": 0.0, 
                "messages": [HumanMessage(content=data)], 
                "error": ""
            }
            
            # Run the agent
            try:
                result = await agent_app.ainvoke(state, config)
                
                # Extract the last message generated by the AI
                messages = result.get("messages", [])
                if messages:
                    ai_response = messages[-1].content
                else:
                    ai_response = "No response generated."
                    
                await manager.send_message(ai_response, user_address)
                
            except Exception as e:
                error_msg = f"Error processing message: {str(e)}"
                await manager.send_message(error_msg, user_address)
                
    except WebSocketDisconnect:
        manager.disconnect(user_address)

# Settings/Dashboard Route
class DashboardResponse(BaseModel):
    user_address: str
    is_active: bool
    tier: int
    active_skills: List[str]

@app.get("/api/dashboard", response_model=DashboardResponse)
def get_dashboard(x_user_address: str = Header(None)):
    if not x_user_address:
        raise HTTPException(status_code=400, detail="X-User-Address header missing")
        
    # In reality, this queries the smart contracts. For now, we mock.
    return DashboardResponse(
        user_address=x_user_address,
        is_active=True,
        tier=2,
        active_skills=["Aave V4 lend/borrow", "GMX V2 perpetuals"]
    )
